export const ENTITY_TABLES = Object.freeze({
  AgentConfig: 'agent_configs',
  AppLabel: 'app_labels',
  Campaign: 'campaigns',
  CampaignSubscription: 'campaign_subscriptions',
  CharacterType: 'character_types',
  CharacterSheet: 'character_sheets',
  ChatMessage: 'chat_messages',
  ContactMessage: 'contact_messages',
  Dossier: 'dossiers',
  DossierCategory: 'dossier_categories',
  DossierComment: 'dossier_comments',
  DossierPage: 'dossier_pages',
  DossierRating: 'dossier_ratings',
  EditableContent: 'editable_contents',
  EpisodeProduction: 'episode_productions',
  GameTheme: 'game_themes',
  GameThemeAsset: 'game_theme_assets',
  GameAIRequest: 'game_ai_requests',
  GameConnection: 'game_connections',
  GameCreation: 'game_creations',
  GameElement: 'game_elements',
  GameInterpretation: 'game_interpretations',
  GameLevel: 'game_levels',
  GameSession: 'game_sessions',
  GameVisit: 'game_visits',
  KnowledgeEntry: 'knowledge_entries',
  MagazinePage: 'magazine_pages',
  MemberEarnings: 'member_earnings',
  MemberPost: 'member_posts',
  MemberProfile: 'member_profiles',
  MembershipPricing: 'membership_pricings',
  Membership: 'memberships',
  Order: 'orders',
  PersonalityQuestion: 'personality_questions',
  PersonalityResult: 'personality_results',
  PostComment: 'post_comments',
  PostLike: 'post_likes',
  PrivateMessage: 'private_messages',
  Product: 'products',
  ProfilePlaceholder: 'profile_placeholders',
  ProfileFanSubscription: 'profile_fan_subscriptions',
  ProfileSponsor: 'profile_sponsors',
  PromoMessagePackage: 'promo_message_packages',
  PromoMessageRequest: 'promo_message_requests',
  QuizQuestion: 'quiz_questions',
  QuizTheme: 'quiz_themes',
  SalonLabel: 'salon_labels',
  SalonStatus: 'salon_statuses',
  ScheduledPromo: 'scheduled_promos',
  SetAsset: 'set_assets',
  ShopSection: 'shop_sections',
  ShopSettings: 'shop_settings',
  SketchTemplate: 'sketch_templates',
  SponsorBracket: 'sponsor_brackets',
  SponsorSale: 'sponsor_sales',
  SimActiveSituation: 'sim_active_situations',
  SimAsset: 'sim_assets',
  SimBelief: 'sim_beliefs',
  SimCharacter: 'sim_characters',
  SimCharacterAction: 'sim_character_actions',
  SimClaim: 'sim_claims',
  SimConsequence: 'sim_consequences',
  SimInformationTransmission: 'sim_information_transmissions',
  SimLocation: 'sim_locations',
  SimObservation: 'sim_observations',
  SimStateChange: 'sim_state_changes',
  SimWorldTime: 'sim_world_times',
  StartingTopic: 'starting_topics',
  StoryCharacter: 'story_characters',
  StorySet: 'story_sets',
  StoryTheme: 'story_themes',
  StoryBlock: 'story_blocks',
  StorySession: 'story_sessions',
  StyleReference: 'style_references',
  TimelineStory: 'timeline_stories',
  TemporaryUser: 'temporary_users',
  TokenPackage: 'token_packages',
  TokenTransaction: 'token_transactions',
  ToolPricing: 'tool_pricings',
  UserTimeline: 'user_timelines',
  UserTokenBalance: 'user_token_balances',
  VaultAsset: 'vault_assets',
  VaultFolder: 'vault_folders',
});

export const MANAGER_TABLES = Object.freeze({
  manageAppLabel: 'app_labels',
  manageCampaign: 'campaigns',
  manageCharacterType: 'character_types',
  manageChatMessage: 'chat_messages',
  manageEditableContent: 'editable_contents',
  manageEpisodeProduction: 'episode_productions',
  manageGameTheme: 'game_themes',
  manageGameThemeAsset: 'game_theme_assets',
  manageKnowledgeEntry: 'knowledge_entries',
  manageMagazinePage: 'magazine_pages',
  manageMemberPost: 'member_posts',
  manageMemberProfile: 'member_profiles',
  manageMembershipPricing: 'membership_pricings',
  manageMonthlyQuizTopic: 'monthly_quiz_topics',
  managePersonalityQuestion: 'personality_questions',
  managePersonalityResult: 'personality_results',
  managePostComment: 'post_comments',
  managePostLike: 'post_likes',
  managePrivateMessage: 'private_messages',
  manageProduct: 'products',
  manageProfilePlaceholder: 'profile_placeholders',
  managePromoMessagePackage: 'promo_message_packages',
  manageQuizQuestion: 'quiz_questions',
  manageQuizTheme: 'quiz_themes',
  manageSalonLabel: 'salon_labels',
  manageShopSection: 'shop_sections',
  manageShopSettings: 'shop_settings',
  manageSketchTemplate: 'sketch_templates',
  manageSponsorBracket: 'sponsor_brackets',
  manageStartingTopic: 'starting_topics',
  manageStoryCharacter: 'story_characters',
  manageStorySet: 'story_sets',
  manageStoryTheme: 'story_themes',
  manageStyleReference: 'style_references',
  manageTimelineStory: 'timeline_stories',
  manageTokenPackage: 'token_packages',
  manageToolPricing: 'tool_pricings',
});

export const PUBLIC_READ_TABLES = new Set([
  'dossier_categories', 'dossier_classes', 'dossiers',
  'editable_contents', 'game_theme_assets', 'game_themes', 'member_posts',
  'member_profiles', 'membership_pricings', 'personality_questions',
  'personality_results', 'products', 'profile_placeholders', 'quiz_questions',
  'quiz_themes', 'shop_sections', 'shop_settings', 'sketch_templates',
  'sponsor_brackets', 'starting_topics', 'story_characters', 'story_sets',
  'story_themes', 'style_references', 'token_packages', 'tool_pricings',
  'temporary_users', 'salon_statuses', 'profile_sponsors', 'profile_fan_subscriptions',
]);
